prd:
  catalog_name: mlops_prd
  schema_name: iepvfeli
acc:
  catalog_name: mlops_acc
  schema_name: iepvfeli
dev:
  catalog_name: mlops_dev
  schema_name: iepvfeli

experiment_name_basic: /Shared/iepv-hotel-reservations-basic
experiment_name_custom: /Shared/iepv-hotel-reservations-custom

parameters:
  n_estimators: 100
  learning_rate: 0.1
  class_weight: 'balanced'

num_features:
  - no_of_adults
  - no_of_children
  - no_of_weekend_nights
  - no_of_week_nights
  - required_car_parking_space
  - lead_time
  - arrival_datetime
  - repeated_guest
  - no_of_previous_cancellations
  - no_of_previous_bookings_not_canceled
  - avg_price_per_room
  - no_of_special_requests
  - arrival_dayofweek
  - arrival_is_weekend
  - arrival_month_num

cat_features:
  - type_of_meal_plan
  - room_type_reserved
  - market_segment_type

target: booking_status
